-- Optimumsite starter schema
-- Generated to satisfy tables referenced in the PHP codebase

CREATE DATABASE IF NOT EXISTS `optimumsite`;
USE `optimumsite`;

CREATE TABLE IF NOT EXISTS `registration` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `indexnumber` VARCHAR(100) DEFAULT NULL,
  `firstname` VARCHAR(100) DEFAULT NULL,
  `lastname` VARCHAR(100) DEFAULT NULL,
  `dob` DATE DEFAULT NULL,
  `gender` VARCHAR(20) DEFAULT NULL,
  `nationality` VARCHAR(100) DEFAULT NULL,
  `qualification` VARCHAR(150) DEFAULT NULL,
  `email` VARCHAR(150) DEFAULT NULL,
  `maritalstatus` VARCHAR(50) DEFAULT NULL,
  `contact` VARCHAR(50) DEFAULT NULL,
  `contactno` VARCHAR(50) DEFAULT NULL,
  `address` VARCHAR(255) DEFAULT NULL,
  `doappoinment` DATE DEFAULT NULL,
  `position` VARCHAR(100) DEFAULT NULL,
  `subject` VARCHAR(100) DEFAULT NULL,
  `username` VARCHAR(100) DEFAULT NULL,
  `password` VARCHAR(255) DEFAULT NULL,
  `status` VARCHAR(50) DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `programtype` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `program` VARCHAR(150) NOT NULL,
  `cost` DECIMAL(10,2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `courses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `programType` VARCHAR(150) DEFAULT NULL,
  `course_name` VARCHAR(200) DEFAULT NULL,
  `programTypeID` INT DEFAULT NULL,
  `course_code` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `exams_setting` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `course` VARCHAR(200) DEFAULT NULL,
  `semester` VARCHAR(50) DEFAULT NULL,
  `timelimit` INT DEFAULT NULL,
  `totalmarks` INT DEFAULT NULL,
  `lecturer` VARCHAR(150) DEFAULT NULL,
  `start_indicator` VARCHAR(10) DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `exams_questions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `staffID` VARCHAR(100) DEFAULT NULL,
  `questionID` INT DEFAULT NULL,
  `question_no` INT DEFAULT NULL,
  `question` TEXT,
  `option1` TEXT,
  `option2` TEXT,
  `option3` TEXT,
  `option4` TEXT,
  `correct_answer` VARCHAR(50) DEFAULT NULL,
  `reason` TEXT,
  `marks` INT DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `tutorclass` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `classname` VARCHAR(150) DEFAULT NULL,
  `course_name` VARCHAR(200) DEFAULT NULL,
  `course_code` VARCHAR(50) DEFAULT NULL,
  `staff_name` VARCHAR(200) DEFAULT NULL,
  `staffID` VARCHAR(100) DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `lesson_upload` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(200) DEFAULT NULL,
  `lesson_class` VARCHAR(150) DEFAULT NULL,
  `lesson_title` VARCHAR(255) DEFAULT NULL,
  `lesson_note` LONGTEXT,
  `lesson_file` VARCHAR(255) DEFAULT NULL,
  `staffID` VARCHAR(100) DEFAULT NULL,
  `staff_name` VARCHAR(200) DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `student_registration` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `indexnumber` VARCHAR(100) DEFAULT NULL,
  `firstname` VARCHAR(100) DEFAULT NULL,
  `lastname` VARCHAR(100) DEFAULT NULL,
  `email` VARCHAR(150) DEFAULT NULL,
  `contact` VARCHAR(50) DEFAULT NULL,
  `placeOfBirth` VARCHAR(150) DEFAULT NULL,
  `Hometown` VARCHAR(150) DEFAULT NULL,
  `region` VARCHAR(100) DEFAULT NULL,
  `nationality` VARCHAR(100) DEFAULT NULL,
  `dateOfAdmission` DATE DEFAULT NULL,
  `active` VARCHAR(50) DEFAULT NULL,
  `programType` VARCHAR(150) DEFAULT NULL,
  `courseSelected` VARCHAR(200) DEFAULT NULL,
  `courseDuration` VARCHAR(100) DEFAULT NULL,
  `fees` VARCHAR(100) DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `message` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) DEFAULT NULL,
  `message` TEXT,
  `messengerID` VARCHAR(100) DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `files_upload` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `file_title` VARCHAR(200) DEFAULT NULL,
  `file_attachment` VARCHAR(255) DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `course_registration` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `studentID` VARCHAR(100) DEFAULT NULL,
  `firstname` VARCHAR(100) DEFAULT NULL,
  `lastname` VARCHAR(100) DEFAULT NULL,
  `course_name` VARCHAR(200) DEFAULT NULL,
  `course_code` VARCHAR(50) DEFAULT NULL,
  `semester` VARCHAR(50) DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `visitor_information` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) DEFAULT NULL,
  `contact` VARCHAR(50) DEFAULT NULL,
  `Address` VARCHAR(255) DEFAULT NULL,
  `purpose` VARCHAR(255) DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `paymentdetails` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(100) DEFAULT NULL,
  `lastname` VARCHAR(100) DEFAULT NULL,
  `indexnumber` VARCHAR(100) DEFAULT NULL,
  `paymentid` VARCHAR(100) DEFAULT NULL,
  `amountowed` DECIMAL(12,2) DEFAULT NULL,
  `feeamount` DECIMAL(12,2) DEFAULT NULL,
  `payment` DECIMAL(12,2) DEFAULT NULL,
  `balance` DECIMAL(12,2) DEFAULT NULL,
  `work_unit` VARCHAR(100) DEFAULT NULL,
  `track` VARCHAR(100) DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `cashindebt` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) DEFAULT NULL,
  `amount` DECIMAL(12,2) DEFAULT NULL,
  `contact` VARCHAR(50) DEFAULT NULL,
  `location` VARCHAR(150) DEFAULT NULL,
  `work_unit` VARCHAR(100) DEFAULT NULL,
  `track` VARCHAR(100) DEFAULT NULL,
  `balance` DECIMAL(12,2) DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `tripirregularexpenses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `itemname` VARCHAR(150) DEFAULT NULL,
  `itemamount` DECIMAL(12,2) DEFAULT NULL,
  `itemimage` VARCHAR(255) DEFAULT NULL,
  `work_unit` VARCHAR(100) DEFAULT NULL,
  `track` VARCHAR(100) DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `tripregularexpenses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `feedingfee` DECIMAL(12,2) DEFAULT NULL,
  `tax` DECIMAL(12,2) DEFAULT NULL,
  `fuel` DECIMAL(12,2) DEFAULT NULL,
  `numberoflitres` DECIMAL(12,2) DEFAULT NULL,
  `totalfuelcost` DECIMAL(12,2) DEFAULT NULL,
  `picture` VARCHAR(255) DEFAULT NULL,
  `remarks` VARCHAR(255) DEFAULT NULL,
  `totalregularexpenses` DECIMAL(12,2) DEFAULT NULL,
  `work_unit` VARCHAR(100) DEFAULT NULL,
  `track` VARCHAR(100) DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Minimal online exam related tables
CREATE TABLE IF NOT EXISTS `online_exam_table` (
  `online_exam_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `online_exam_datetime` DATETIME DEFAULT NULL,
  `marks_per_right_answer` INT DEFAULT 1,
  `marks_per_wrong_answer` INT DEFAULT 0,
  `online_exam_status` VARCHAR(50) DEFAULT NULL,
  `total_question` INT DEFAULT NULL,
  PRIMARY KEY (`online_exam_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `question_table` (
  `question_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `online_exam_id` INT UNSIGNED DEFAULT NULL,
  `question_title` TEXT,
  `answer_option` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`question_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `user_exam_enroll_table` (
  `user_exam_enroll_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `online_exam_id` INT UNSIGNED DEFAULT NULL,
  `user_id` INT UNSIGNED DEFAULT NULL,
  `status` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`user_exam_enroll_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `user_exam_question_answer` (
  `user_exam_question_answer_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_exam_enroll_id` INT UNSIGNED DEFAULT NULL,
  `question_id` INT UNSIGNED DEFAULT NULL,
  `user_answer_option` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`user_exam_question_answer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;